// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using System.Collections;
namespace IMDBTest {
    /// <summary>
    ///This is a test class for SixDegrees.IMDBTools and is intended
    ///to contain all SixDegrees.IMDBTools Unit Tests
    ///</summary>
    [TestClass()]
    public class IMDBToolsTest {

        [TestMethod]
        public void GetMovieCode() {
            List<string> expectedCodes = new List<string>(), actualCodes = new List<string>();

            actualCodes.Add(SixDegrees.IMDBTools.GetMovieCode("Ocean's Thirteen"));
            expectedCodes.Add("0496806");

            actualCodes.Add(SixDegrees.IMDBTools.GetMovieCode("Oceans Thirteen"));
            expectedCodes.Add("0496806");

            actualCodes.Add(SixDegrees.IMDBTools.GetMovieCode("Ocean's 13"));
            expectedCodes.Add("0496806");

            for (int i = 0; i < expectedCodes.Count; i++) {
                WriteResult(expectedCodes[i], actualCodes[i]);
                Assert.AreEqual(expectedCodes[i], actualCodes[i]);
            }
        }

        [TestMethod]
        public void GetActorCode() {
            List<string> expectedCodes = new List<string>(), actualCodes = new List<string>();

            actualCodes.Add(SixDegrees.IMDBTools.GetNameCode("Jennifer Connelly"));
            expectedCodes.Add("0000124");

            actualCodes.Add(SixDegrees.IMDBTools.GetNameCode("Jessica Alba"));
            expectedCodes.Add("0004695");

            actualCodes.Add(SixDegrees.IMDBTools.GetNameCode("Bill Murray"));
            expectedCodes.Add("0000195");

            for (int i = 0; i < expectedCodes.Count; i++) {
                WriteResult(expectedCodes[i], actualCodes[i]);
                Assert.AreEqual(expectedCodes[i], actualCodes[i]);
            }
        }

        private void WriteResult(string expected, string actual) {
            Console.WriteLine("Should be:\t{0}\tIs:\t{1}", expected, actual);
        }

    }


}
