// ------------------------------------------------------------------------------
//<autogenerated>
//        This code was generated by Microsoft Visual Studio Team System 2005.
//
//        Changes to this file may cause incorrect behavior and will be lost if
//        the code is regenerated.
//</autogenerated>
//------------------------------------------------------------------------------
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace IMDBTest
{
[System.Diagnostics.DebuggerStepThrough()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
internal class BaseAccessor {
    
    protected Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject m_privateObject;
    
    protected BaseAccessor(object target, Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType type) {
        m_privateObject = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject(target, type);
    }
    
    protected BaseAccessor(Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType type) : 
            this(null, type) {
    }
    
    internal virtual object Target {
        get {
            return m_privateObject.Target;
        }
    }
    
    public override string ToString() {
        return this.Target.ToString();
    }
    
    public override bool Equals(object obj) {
        if (typeof(BaseAccessor).IsInstanceOfType(obj)) {
            obj = ((BaseAccessor)(obj)).Target;
        }
        return this.Target.Equals(obj);
    }
    
    public override int GetHashCode() {
        return this.Target.GetHashCode();
    }
}
[System.Diagnostics.DebuggerStepThrough()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
internal class SixDegrees_IMDBFormAccessor : BaseAccessor {
    
    protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType(typeof(global::SixDegrees.IMDBForm));
    
    internal SixDegrees_IMDBFormAccessor(global::SixDegrees.IMDBForm target) : 
            base(target, m_privateType) {
    }
    
    internal global::System.Windows.Forms.TreeNode _selectedNode {
        get {
            global::System.Windows.Forms.TreeNode ret = ((global::System.Windows.Forms.TreeNode)(m_privateObject.GetField("_selectedNode")));
            return ret;
        }
        set {
            m_privateObject.SetField("_selectedNode", value);
        }
    }
    
    internal bool _isName {
        get {
            bool ret = ((bool)(m_privateObject.GetField("_isName")));
            return ret;
        }
        set {
            m_privateObject.SetField("_isName", value);
        }
    }
    
    internal bool _browserHidden {
        get {
            bool ret = ((bool)(m_privateObject.GetField("_browserHidden")));
            return ret;
        }
        set {
            m_privateObject.SetField("_browserHidden", value);
        }
    }
    
    internal global::System.ComponentModel.IContainer components {
        get {
            global::System.ComponentModel.IContainer ret = ((global::System.ComponentModel.IContainer)(m_privateObject.GetField("components")));
            return ret;
        }
        set {
            m_privateObject.SetField("components", value);
        }
    }
    
    internal global::System.Windows.Forms.Panel actionP {
        get {
            global::System.Windows.Forms.Panel ret = ((global::System.Windows.Forms.Panel)(m_privateObject.GetField("actionP")));
            return ret;
        }
        set {
            m_privateObject.SetField("actionP", value);
        }
    }
    
    internal global::System.Windows.Forms.GroupBox groupBox1 {
        get {
            global::System.Windows.Forms.GroupBox ret = ((global::System.Windows.Forms.GroupBox)(m_privateObject.GetField("groupBox1")));
            return ret;
        }
        set {
            m_privateObject.SetField("groupBox1", value);
        }
    }
    
    internal global::System.Windows.Forms.Button searchB {
        get {
            global::System.Windows.Forms.Button ret = ((global::System.Windows.Forms.Button)(m_privateObject.GetField("searchB")));
            return ret;
        }
        set {
            m_privateObject.SetField("searchB", value);
        }
    }
    
    internal global::System.Windows.Forms.TextBox searchTB {
        get {
            global::System.Windows.Forms.TextBox ret = ((global::System.Windows.Forms.TextBox)(m_privateObject.GetField("searchTB")));
            return ret;
        }
        set {
            m_privateObject.SetField("searchTB", value);
        }
    }
    
    internal global::System.Windows.Forms.RadioButton titleRB {
        get {
            global::System.Windows.Forms.RadioButton ret = ((global::System.Windows.Forms.RadioButton)(m_privateObject.GetField("titleRB")));
            return ret;
        }
        set {
            m_privateObject.SetField("titleRB", value);
        }
    }
    
    internal global::System.Windows.Forms.RadioButton nameRB {
        get {
            global::System.Windows.Forms.RadioButton ret = ((global::System.Windows.Forms.RadioButton)(m_privateObject.GetField("nameRB")));
            return ret;
        }
        set {
            m_privateObject.SetField("nameRB", value);
        }
    }
    
    internal global::System.Windows.Forms.Button button2 {
        get {
            global::System.Windows.Forms.Button ret = ((global::System.Windows.Forms.Button)(m_privateObject.GetField("button2")));
            return ret;
        }
        set {
            m_privateObject.SetField("button2", value);
        }
    }
    
    internal global::System.Windows.Forms.Button button1 {
        get {
            global::System.Windows.Forms.Button ret = ((global::System.Windows.Forms.Button)(m_privateObject.GetField("button1")));
            return ret;
        }
        set {
            m_privateObject.SetField("button1", value);
        }
    }
    
    internal global::System.Windows.Forms.SplitContainer splitContainer1 {
        get {
            global::System.Windows.Forms.SplitContainer ret = ((global::System.Windows.Forms.SplitContainer)(m_privateObject.GetField("splitContainer1")));
            return ret;
        }
        set {
            m_privateObject.SetField("splitContainer1", value);
        }
    }
    
    internal global::System.Windows.Forms.TreeView imdbTV {
        get {
            global::System.Windows.Forms.TreeView ret = ((global::System.Windows.Forms.TreeView)(m_privateObject.GetField("imdbTV")));
            return ret;
        }
        set {
            m_privateObject.SetField("imdbTV", value);
        }
    }
    
    internal global::System.Windows.Forms.ProgressBar waitPB {
        get {
            global::System.Windows.Forms.ProgressBar ret = ((global::System.Windows.Forms.ProgressBar)(m_privateObject.GetField("waitPB")));
            return ret;
        }
        set {
            m_privateObject.SetField("waitPB", value);
        }
    }
    
    internal global::System.ComponentModel.BackgroundWorker imdbBW {
        get {
            global::System.ComponentModel.BackgroundWorker ret = ((global::System.ComponentModel.BackgroundWorker)(m_privateObject.GetField("imdbBW")));
            return ret;
        }
        set {
            m_privateObject.SetField("imdbBW", value);
        }
    }
    
    internal global::SixDegrees.TransparentPanel waitP {
        get {
            global::SixDegrees.TransparentPanel ret = ((global::SixDegrees.TransparentPanel)(m_privateObject.GetField("waitP")));
            return ret;
        }
        set {
            m_privateObject.SetField("waitP", value);
        }
    }
    
    internal global::System.ComponentModel.BackgroundWorker expandBW {
        get {
            global::System.ComponentModel.BackgroundWorker ret = ((global::System.ComponentModel.BackgroundWorker)(m_privateObject.GetField("expandBW")));
            return ret;
        }
        set {
            m_privateObject.SetField("expandBW", value);
        }
    }
    
    internal global::System.Windows.Forms.ImageList treeIL {
        get {
            global::System.Windows.Forms.ImageList ret = ((global::System.Windows.Forms.ImageList)(m_privateObject.GetField("treeIL")));
            return ret;
        }
        set {
            m_privateObject.SetField("treeIL", value);
        }
    }
    
    internal global::System.Windows.Forms.WebBrowser imdbWB {
        get {
            global::System.Windows.Forms.WebBrowser ret = ((global::System.Windows.Forms.WebBrowser)(m_privateObject.GetField("imdbWB")));
            return ret;
        }
        set {
            m_privateObject.SetField("imdbWB", value);
        }
    }
    
    internal global::System.Windows.Forms.Label statusL {
        get {
            global::System.Windows.Forms.Label ret = ((global::System.Windows.Forms.Label)(m_privateObject.GetField("statusL")));
            return ret;
        }
        set {
            m_privateObject.SetField("statusL", value);
        }
    }
    
    internal void searchB_Click(object sender, global::System.EventArgs e) {
        object[] args = new object[] {
                sender,
                e};
        m_privateObject.Invoke("searchB_Click", new System.Type[] {
                    typeof(object),
                    typeof(global::System.EventArgs)}, args);
    }
    
    internal void imdbTV_NodeMouseClick(object sender, global::System.Windows.Forms.TreeNodeMouseClickEventArgs e) {
        object[] args = new object[] {
                sender,
                e};
        m_privateObject.Invoke("imdbTV_NodeMouseClick", new System.Type[] {
                    typeof(object),
                    typeof(global::System.Windows.Forms.TreeNodeMouseClickEventArgs)}, args);
    }
    
    internal void imdbTV_AfterExpand(object sender, global::System.Windows.Forms.TreeViewEventArgs e) {
        object[] args = new object[] {
                sender,
                e};
        m_privateObject.Invoke("imdbTV_AfterExpand", new System.Type[] {
                    typeof(object),
                    typeof(global::System.Windows.Forms.TreeViewEventArgs)}, args);
    }
    
    internal void imdbTV_MouseDown(object sender, global::System.Windows.Forms.MouseEventArgs e) {
        object[] args = new object[] {
                sender,
                e};
        m_privateObject.Invoke("imdbTV_MouseDown", new System.Type[] {
                    typeof(object),
                    typeof(global::System.Windows.Forms.MouseEventArgs)}, args);
    }
    
    internal void waitP_Paint(object sender, global::System.Windows.Forms.PaintEventArgs e) {
        object[] args = new object[] {
                sender,
                e};
        m_privateObject.Invoke("waitP_Paint", new System.Type[] {
                    typeof(object),
                    typeof(global::System.Windows.Forms.PaintEventArgs)}, args);
    }
    
    internal void imdbBW_DoWork(object sender, global::System.ComponentModel.DoWorkEventArgs e) {
        object[] args = new object[] {
                sender,
                e};
        m_privateObject.Invoke("imdbBW_DoWork", new System.Type[] {
                    typeof(object),
                    typeof(global::System.ComponentModel.DoWorkEventArgs)}, args);
    }
    
    internal void worker_ProgressChanged(object sender, global::System.ComponentModel.ProgressChangedEventArgs e) {
        object[] args = new object[] {
                sender,
                e};
        m_privateObject.Invoke("worker_ProgressChanged", new System.Type[] {
                    typeof(object),
                    typeof(global::System.ComponentModel.ProgressChangedEventArgs)}, args);
    }
    
    internal void imdbBW_RunWorkerCompleted(object sender, global::System.ComponentModel.RunWorkerCompletedEventArgs e) {
        object[] args = new object[] {
                sender,
                e};
        m_privateObject.Invoke("imdbBW_RunWorkerCompleted", new System.Type[] {
                    typeof(object),
                    typeof(global::System.ComponentModel.RunWorkerCompletedEventArgs)}, args);
    }
    
    internal void UpdateStatus(string status, bool visible) {
        object[] args = new object[] {
                status,
                visible};
        m_privateObject.Invoke("UpdateStatus", new System.Type[] {
                    typeof(string),
                    typeof(bool)}, args);
    }
    
    internal void expandBW_DoWork(object sender, global::System.ComponentModel.DoWorkEventArgs e) {
        object[] args = new object[] {
                sender,
                e};
        m_privateObject.Invoke("expandBW_DoWork", new System.Type[] {
                    typeof(object),
                    typeof(global::System.ComponentModel.DoWorkEventArgs)}, args);
    }
    
    internal void expandBW_RunWorkerCompleted(object sender, global::System.ComponentModel.RunWorkerCompletedEventArgs e) {
        object[] args = new object[] {
                sender,
                e};
        m_privateObject.Invoke("expandBW_RunWorkerCompleted", new System.Type[] {
                    typeof(object),
                    typeof(global::System.ComponentModel.RunWorkerCompletedEventArgs)}, args);
    }
    
    internal void splitContainer1_DoubleClick(object sender, global::System.EventArgs e) {
        object[] args = new object[] {
                sender,
                e};
        m_privateObject.Invoke("splitContainer1_DoubleClick", new System.Type[] {
                    typeof(object),
                    typeof(global::System.EventArgs)}, args);
    }
    
    internal void Dispose(bool disposing) {
        object[] args = new object[] {
                disposing};
        m_privateObject.Invoke("Dispose", new System.Type[] {
                    typeof(bool)}, args);
    }
    
    internal void InitializeComponent() {
        object[] args = new object[0];
        m_privateObject.Invoke("InitializeComponent", new System.Type[0], args);
    }
}
}
