//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SixDegrees.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SixDegrees.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap movieicon {
            get {
                object obj = ResourceManager.GetObject("movieicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap personicon {
            get {
                object obj = ResourceManager.GetObject("personicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a\\s+?href=\\\&quot;/name/nm(?&lt;NameCode&gt;\\d{7}).*?&gt;(?&lt;Name&gt;.+?)&lt;/a&gt;.
        /// </summary>
        internal static string Regex_NameAndCodeFromLink {
            get {
                return ResourceManager.GetString("Regex_NameAndCodeFromLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a\\s+?href=\\\&quot;/title/tt(?&lt;TitleCode&gt;\\d{7}).*?&gt;(?&lt;Title&gt;.+?)&lt;/a&gt;.
        /// </summary>
        internal static string Regex_TitleAndCodeFromLink {
            get {
                return ResourceManager.GetString("Regex_TitleAndCodeFromLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://imdb.com/name/nm.
        /// </summary>
        internal static string Url_Page_Name {
            get {
                return ResourceManager.GetString("Url_Page_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://imdb.com/title/tt.
        /// </summary>
        internal static string Url_Page_Title {
            get {
                return ResourceManager.GetString("Url_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://imdb.com/find?s=all&amp;q=.
        /// </summary>
        internal static string Url_Search_All {
            get {
                return ResourceManager.GetString("Url_Search_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://imdb.com/find?s=nm&amp;q=.
        /// </summary>
        internal static string Url_Search_Name {
            get {
                return ResourceManager.GetString("Url_Search_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://imdb.com/find?s=tt&amp;q=.
        /// </summary>
        internal static string Url_Search_Title {
            get {
                return ResourceManager.GetString("Url_Search_Title", resourceCulture);
            }
        }
    }
}
